### ISSUE TITLE
Add check list.json also add pdf 

### ISSUE THREAD

**Issue by tk-t0n0y** [dsopas/MindAPI#8]
Add checklist

**Comment by dsopas** [comment]
@tk-t0n0y Can you be more specific? 
If you're asking for another format besides markdown for the mind map, you have some tools that can convert it for you. Also, markmap (what is being used to generate the mind map from the markdown) renders in SVG so I guess is also possible to convert it to PDF.

Does this solves your request?

**Comment by jsnode2121212** [comment]
Hello , how to download this mindmap ?

**Comment by dsopas** [comment]
@jsnode2121212 its currently on the todo list :)
